export const PULL_TO_REFRESH_OVERSCROLL_THRESHOLD = 80
export const PULL_TO_REFRESH_HIDE_DELAY_MS = 220
export const PULL_TO_REFRESH_IOS_TOP_INSET_PX = 48
export const PULL_TO_REFRESH_ANDROID_NATIVE_OFFSET_DP = -280
