export const PULL_TO_REFRESH_OVERSCROLL_THRESHOLD = 80
export const PULL_TO_REFRESH_HIDE_DELAY_MS = 220
export const PULL_TO_REFRESH_IOS_TOP_INSET_PX = 48
export const PULL_TO_REFRESH_ANDROID_NATIVE_OFFSET_DP = -280
export const PULL_TO_REFRESH_MAX_PULL_VISUAL_PX = 120

export const PULL_TO_REFRESH_IOS_RESET_BELOW_Y = 10
export const PULL_TO_REFRESH_IOS_CLEAR_AFTER_REFRESH_MS = 910
export const PULL_TO_REFRESH_IOS_CLEAR_AFTER_RELEASE_MS = 260

export const PULL_TO_REFRESH_ANDROID_STEP_PX = 1.75
export const PULL_TO_REFRESH_ANDROID_CLEAR_BELOW_Y = 10
