export const PLAYGROUND_LINKS: { labelKey: string; href: string }[] = [
  { labelKey: 'playground.linksMyList', href: '/playground/my-list' },
  { labelKey: 'playground.linksSwipeableItem', href: '/playground/swipeable-item' },
  { labelKey: 'playground.linksForm', href: '/playground/form' },
  { labelKey: 'playground.linksButtons', href: '/playground/buttons' },
  { labelKey: 'playground.linksChips', href: '/playground/chips' },
  { labelKey: 'playground.linksCheckbox', href: '/playground/checkbox' },
  { labelKey: 'playground.linksSwitch', href: '/playground/switch' },
  { labelKey: 'playground.linksDropdown', href: '/playground/dropdown' },
  { labelKey: 'playground.linksDatePicker', href: '/playground/date-picker' },
  { labelKey: 'playground.linksWheelPicker', href: '/playground/wheel-picker' },
  { labelKey: 'playground.linksCounter', href: '/playground/counter' },
  { labelKey: 'playground.linksToast', href: '/playground/toast' },
  { labelKey: 'playground.linksBottomSheet', href: '/playground/bottom-sheet' },
  { labelKey: 'playground.linksTextInput', href: '/playground/text-input' },
  { labelKey: 'playground.linksAlert', href: '/playground/alert' },
  { labelKey: 'playground.linksImage', href: '/playground/image' },
]
