export const PLAYGROUND_LINKS: { label: string; href: string }[] = [
  { label: 'My List', href: '/playground/my-list' },
  { label: 'Form (RHF + Zod)', href: '/playground/form' },
  { label: 'Buttons', href: '/playground/buttons' },
  { label: 'Chips', href: '/playground/chips' },
  { label: 'Checkbox', href: '/playground/checkbox' },
  { label: 'Switch', href: '/playground/switch' },
  { label: 'Dropdown', href: '/playground/dropdown' },
  { label: 'Date Picker', href: '/playground/date-picker' },
  { label: 'Wheel Picker', href: '/playground/wheel-picker' },
  { label: 'Counter', href: '/playground/counter' },
  { label: 'Toast & Confirmation', href: '/playground/toast' },
  { label: 'Bottom Sheet', href: '/playground/bottom-sheet' },
  { label: 'Text Input', href: '/playground/text-input' },
  { label: 'Alert', href: '/playground/alert' },
  { label: 'Image', href: '/playground/image' },
]
